import { HistoryItem, WordDefinition } from "@/types/translation";

export const SAMPLE_HISTORY: HistoryItem[] = [
  { id: "1", word: "performance" },
  { id: "2", word: "suburb" },
  { id: "3", word: "sanity" },
  { id: "4", word: "under the weather" },
  { id: "5", word: "nostalgic" },
  { id: "6", word: "ability" },
  { id: "7", word: "abandon" },
  { id: "8", word: "able" },
  { id: "9", word: "about" },
  { id: "10", word: "above" },
];

// Sample word list for suggestions
export const WORD_LIST = [
  "band",
  "bandage",
  "bandaged",
  "bandager",
  "bandagers",
  "bandages",
  "bandaging",
  "banded",
  "banding",
  "bands",
  "bandwidth",
  "book",
  "booking",
  "booklet",
  "bookmark",
  "books",
  "bookshelf",
  "bookstore",
  "performance",
  "perform",
  "performer",
  "performing",
  "suburb",
  "suburban",
  "suburbanite",
  "suburbs",
  "sanity",
  "sane",
  "sanitize",
  "sanitary",
  "nostalgic",
  "nostalgia",
  "hello",
  "help",
  "helpful",
  "helping",
  "helper",
  "world",
  "work",
  "worker",
  "working",
  "workout",
  "workplace",
  "ability",
  "able",
  "abandon",
  "about",
  "above",
  "abroad",
  "absence",
  "absolute",
  "abortion",
];

// Helper function to map part of speech from English to Vietnamese
function mapPartOfSpeech(partOfSpeech: string[]): string {
  const pos = partOfSpeech[0]?.toLowerCase() || "";
  if (pos === "noun") return "danh từ";
  if (pos === "verb") return "động từ";
  if (pos === "adjective") return "tính từ";
  if (pos === "adverb") return "trạng từ";
  if (pos === "preposition") return "giới từ";
  if (pos === "determiner") return "mạo từ";
  return "danh từ"; // Default
}

export const SAMPLE_DEFINITIONS: { [key: string]: WordDefinition } = {
  band: {
    word: "band",
    pronunciation: {
      us: "/bænd/",
      uk: "/bænd/",
    },
    definitions: [
      {
        id: "1",
        word: "ban nhạc, nhóm nhạc",
        wordType: "danh từ",
        meaning: "Một nhóm nhạc sĩ biểu diễn cùng nhau",
        examples: ["The band played at the festival last night."],
        examplesVi: ["Ban nhạc đã biểu diễn tại lễ hội tối qua."],
        saved: false,
      },
      {
        id: "2",
        word: "dải, băng, dây",
        wordType: "danh từ",
        meaning: "Một dải vật liệu mỏng, phẳng dùng để buộc, cố định hoặc trang trí thứ gì đó",
        examples: ["She tied her hair with a rubber band."],
        examplesVi: ["Cô ấy buộc tóc bằng một sợi dây cao su."],
        saved: false,
      },
      {
        id: "3",
        word: "sọc, vạch, vòng",
        wordType: "danh từ",
        meaning: "Một sọc hoặc vòng có màu sắc hoặc kết cấu khác trên vật gì đó",
        examples: ["The cat has a white band around its neck."],
        examplesVi: ["Con mèo có một vòng trắng quanh cổ."],
        saved: false,
      },
      {
        id: "4",
        word: "dải, băng tần, khoảng",
        wordType: "danh từ",
        meaning: "Một phạm vi cụ thể của các giá trị, tần số hoặc phép đo trong một quang phổ",
        examples: ["This radio operates in the FM band."],
        examplesVi: ["Đài radio này hoạt động trong băng tần FM."],
        saved: false,
      },
      {
        id: "5",
        word: "tập hợp, liên kết, đoàn kết",
        wordType: "động từ",
        meaning: "Tập hợp thành nhóm hoặc đoàn kết vì một mục đích chung",
        examples: ["The workers banded together to demand better wages."],
        examplesVi: ["Các công nhân đã đoàn kết lại để đòi lương cao hơn."],
        saved: false,
      },
      {
        id: "6",
        word: "nhóm, băng nhóm, hội",
        wordType: "danh từ",
        meaning: "Một nhóm người có mục đích hoặc đặc điểm chung",
        examples: ["A band of rebels attacked the village."],
        examplesVi: ["Một nhóm phiến quân đã tấn công ngôi làng."],
        saved: false,
      },
      {
        id: "7",
        word: "đánh dấu, vẽ sọc, đánh vòng",
        wordType: "động từ",
        meaning: "Đánh dấu hoặc bao quanh bằng một sọc hoặc vòng",
        examples: ["The tree trunk was banded with red paint."],
        examplesVi: ["Thân cây được đánh dấu bằng sơn đỏ."],
        saved: false,
      },
      {
        id: "8",
        word: "đeo vòng, gắn băng, đánh dấu",
        wordType: "động từ",
        meaning: "Gắn một vòng hoặc băng vào vật gì đó, đặc biệt là động vật để nhận dạng",
        examples: ["Scientists banded the birds to track their migration."],
        examplesVi: ["Các nhà khoa học đã đeo vòng cho các con chim để theo dõi di cư."],
        saved: false,
      },
      {
        id: "9",
        word: "nhẫn, vòng",
        wordType: "danh từ",
        meaning: "Một chiếc nhẫn phẳng đeo làm đồ trang sức, đặc biệt là nhẫn cưới",
        examples: ["He bought a gold band for their anniversary."],
        examplesVi: ["Anh ấy mua một chiếc nhẫn vàng cho lễ kỷ niệm của họ."],
        saved: false,
      },
      {
        id: "10",
        word: "dây đai, băng truyền",
        wordType: "danh từ",
        meaning: "Một dây đai truyền động trong máy móc để kết nối các bộ phận quay",
        examples: ["The band on the motor needs to be replaced."],
        examplesVi: ["Dây đai trên động cơ cần được thay thế."],
        saved: false,
      },
    ],
  },
  ability: {
    word: "ability",
    pronunciation: {
      us: "/əˈbɪləti/",
      uk: "/əˈbɪləti/",
    },
    definitions: [
      {
        id: "1",
        word: "khả năng, năng lực",
        wordType: "danh từ",
        meaning: "Khả năng hoặc sức mạnh để làm điều gì đó về thể chất hoặc tinh thần.",
        examples: ["She has the ability to solve complex problems."],
        examplesVi: ["Cô ấy có khả năng giải quyết các vấn đề phức tạp."],
        saved: false,
        popularity: 5,
      },
      {
        id: "2",
        word: "tài năng, kỹ năng, năng khiếu",
        wordType: "danh từ",
        meaning: "Một tài năng, kỹ năng hoặc năng lực cụ thể trong một lĩnh vực nhất định.",
        examples: ["He has a natural ability for music."],
        examplesVi: ["Anh ấy có tài năng bẩm sinh về âm nhạc."],
        saved: false,
        popularity: 5,
      },
      {
        id: "3",
        word: "thẩm quyền, quyền hạn",
        wordType: "danh từ",
        meaning: "Quyền hạn pháp lý hoặc chính thức để hành động hoặc đưa ra quyết định.",
        examples: ["The manager has the ability to approve expenses."],
        examplesVi: ["Người quản lý có thẩm quyền phê duyệt chi phí."],
        saved: false,
        popularity: 3,
      },
      {
        id: "4",
        word: "khả năng thực hiện, năng lực tiềm năng",
        wordType: "danh từ",
        meaning:
          "Phẩm chất có thể thực hiện tốt; năng lực được đo bằng tiềm năng hơn là hiệu suất thực tế.",
        examples: ["The test measures your ability to learn new skills."],
        examplesVi: ["Bài kiểm tra đo lường khả năng học kỹ năng mới của bạn."],
        saved: false,
        popularity: 2,
      },
    ],
  },
  abandon: {
    word: "abandon",
    pronunciation: {
      us: "/əˈbændən/",
      uk: "/əˈbændən/",
    },
    definitions: [
      {
        id: "1",
        word: "bỏ rơi, từ bỏ",
        wordType: "động từ",
        meaning:
          "Bỏ rơi hoàn toàn ai đó hoặc cái gì đó, đặc biệt khi người ta nên ở lại hoặc có trách nhiệm phải ở lại.",
        examples: ["He abandoned his family when they needed him most."],
        examplesVi: ["Anh ta bỏ rơi gia đình khi họ cần anh ta nhất."],
        saved: false,
        popularity: 5,
      },
      {
        id: "2",
        word: "từ bỏ, bỏ cuộc",
        wordType: "động từ",
        meaning: "Ngừng làm hoặc theo đuổi điều gì đó, đặc biệt là trước khi hoàn thành; đầu hàng.",
        examples: ["They abandoned the project due to lack of funds."],
        examplesVi: ["Họ từ bỏ dự án vì thiếu kinh phí."],
        saved: false,
        popularity: 5,
      },
      {
        id: "3",
        word: "buông thả, để mặc",
        wordType: "động từ",
        meaning:
          "Dâng hiến bản thân hoàn toàn cho một cảm xúc hoặc sự thôi thúc mà không kiềm chế.",
        examples: ["She abandoned herself to grief after the loss."],
        examplesVi: ["Cô ấy buông mình vào nỗi buồn sau mất mát."],
        saved: false,
        popularity: 4,
      },
      {
        id: "4",
        word: "sự phóng khoáng, sự tự do",
        wordType: "danh từ",
        meaning:
          "Sự thiếu ức chế hoặc kiềm chế hoàn toàn; sự tự do phóng túng trong cách cư xử hoặc hành động.",
        examples: ["The dancers moved with joyful abandon."],
        examplesVi: ["Các vũ công chuyển động với sự phóng khoáng vui vẻ."],
        saved: false,
        popularity: 3,
      },
      {
        id: "5",
        word: "từ bỏ quyền, khước từ",
        wordType: "động từ",
        meaning: "Từ bỏ hoặc nhượng lại một quyền pháp lý, yêu cầu, hoặc quyền lợi.",
        examples: ["He abandoned his claim to the inheritance."],
        examplesVi: ["Anh ta từ bỏ quyền thừa kế của mình."],
        saved: false,
        popularity: 2,
      },
    ],
  },
  able: {
    word: "able",
    pronunciation: {
      us: "/ˈeɪbəl/",
      uk: "/ˈeɪbəl/",
    },
    definitions: [
      {
        id: "1",
        word: "có khả năng, có thể",
        wordType: "tính từ",
        meaning: "Có quyền lực, kỹ năng, phương tiện hoặc cơ hội để làm điều gì đó.",
        examples: ["She is able to speak three languages."],
        examplesVi: ["Cô ấy có thể nói ba thứ tiếng."],
        saved: false,
        popularity: 5,
      },
      {
        id: "2",
        word: "tài năng, có năng lực, giỏi",
        wordType: "tính từ",
        meaning: "Có kỹ năng, trình độ hoặc trí thông minh đáng kể; có năng lực hoặc tài năng.",
        examples: ["He is an able teacher."],
        examplesVi: ["Anh ấy là một giáo viên giỏi."],
        saved: false,
        popularity: 4,
      },
      {
        id: "3",
        word: "có thẩm quyền, hợp pháp",
        wordType: "tính từ",
        meaning: "Có thẩm quyền hoặc quyền hạn hợp pháp hoặc chính thức để hành động.",
        examples: ["Only able citizens can vote."],
        examplesVi: ["Chỉ những công dân có thẩm quyền mới có thể bỏ phiếu."],
        saved: false,
        popularity: 2,
      },
    ],
  },
  about: {
    word: "about",
    pronunciation: {
      us: "/əˈbaʊt/",
      uk: "/əˈbaʊt/",
    },
    definitions: [
      {
        id: "1",
        word: "về, liên quan đến",
        wordType: "giới từ",
        meaning: "Liên quan hoặc có quan hệ đến một chủ đề hoặc đề tài cụ thể.",
        examples: ["We talked about the weather."],
        examplesVi: ["Chúng tôi nói chuyện về thời tiết."],
        saved: false,
        popularity: 5,
      },
      {
        id: "2",
        word: "khoảng, xấp xỉ",
        wordType: "trạng từ",
        meaning: "Xấp xỉ hoặc gần đúng (dùng với số hoặc số lượng).",
        examples: ["It costs about ten dollars."],
        examplesVi: ["Nó có giá khoảng mười đô la."],
        saved: false,
        popularity: 5,
      },
      {
        id: "3",
        word: "ở, quanh, gần",
        wordType: "giới từ",
        meaning: "Nằm ở hoặc xung quanh một địa điểm cụ thể.",
        examples: ["There are shops about the city."],
        examplesVi: ["Có các cửa hàng quanh thành phố."],
        saved: false,
        popularity: 4,
      },
      {
        id: "4",
        word: "quay lại, đảo ngược",
        wordType: "trạng từ",
        meaning: "Theo hướng ngược lại hoặc quay mặt về phía khác.",
        examples: ["He turned about and walked away."],
        examplesVi: ["Anh ấy quay lại và bước đi."],
        saved: false,
        popularity: 4,
      },
      {
        id: "5",
        word: "đang làm, bận rộn với",
        wordType: "giới từ",
        meaning: "Tham gia hoặc bận rộn với một hoạt động.",
        examples: ["What are you about today?"],
        examplesVi: ["Hôm nay bạn đang làm gì?"],
        saved: false,
        popularity: 3,
      },
      {
        id: "6",
        word: "có mặt, đang ở đây",
        wordType: "tính từ",
        meaning:
          'Có mặt hoặc di chuyển quanh một nơi (được dùng như vị ngữ, ví dụ "mọi người đang ở đây").',
        examples: ["Is anyone about?"],
        examplesVi: ["Có ai ở đây không?"],
        saved: false,
        popularity: 3,
      },
      {
        id: "7",
        word: "đây đó, khắp nơi",
        wordType: "trạng từ",
        meaning: "Đây đó trong nhiều hướng hoặc nhiều nơi khác nhau.",
        examples: ["Papers were scattered about."],
        examplesVi: ["Giấy tờ bị rải rác khắp nơi."],
        saved: false,
        popularity: 2,
      },
      {
        id: "8",
        word: "về, liên quan tới",
        wordType: "giới từ",
        meaning: "Về vấn đề hoặc có liên quan đến.",
        examples: ["A book about history."],
        examplesVi: ["Một cuốn sách về lịch sử."],
        saved: false,
        popularity: 2,
      },
    ],
  },
  above: {
    word: "above",
    pronunciation: {
      us: "/əˈbʌv/",
      uk: "/əˈbʌv/",
    },
    definitions: [
      {
        id: "1",
        word: "trên, phía trên",
        wordType: "giới từ",
        meaning: "Ở mức độ hoặc vị trí cao hơn; phía trên.",
        examples: ["The bird flew above the trees."],
        examplesVi: ["Con chim bay trên những tán cây."],
        saved: false,
        popularity: 5,
      },
      {
        id: "2",
        word: "hơn, trên",
        wordType: "giới từ",
        meaning: "Nhiều hơn về số lượng, mức độ hoặc đo lường.",
        examples: ["Temperatures above 30 degrees are common here."],
        examplesVi: ["Nhiệt độ trên 30 độ rất phổ biến ở đây."],
        saved: false,
        popularity: 5,
      },
      {
        id: "3",
        word: "ở trên, phía trên",
        wordType: "trạng từ",
        meaning: "Ở hoặc đến một nơi cao hơn; phía trên đầu.",
        examples: ["Look at the clouds above."],
        examplesVi: ["Hãy nhìn những đám mây ở trên."],
        saved: false,
        popularity: 5,
      },
      {
        id: "4",
        word: "cao hơn, trên",
        wordType: "giới từ",
        meaning: "Cao hơn về cấp bậc, địa vị hoặc quyền lực.",
        examples: ["She is above me in the company hierarchy."],
        examplesVi: ["Cô ấy cao hơn tôi trong hệ thống cấp bậc công ty."],
        saved: false,
        popularity: 4,
      },
      {
        id: "5",
        word: "ở trên, nói trên",
        wordType: "tính từ",
        meaning: "Được đề cập hoặc viết trước đó trong văn bản hoặc tài liệu.",
        examples: ["Please refer to the above information."],
        examplesVi: ["Vui lòng tham khảo thông tin nói trên."],
        saved: false,
        popularity: 4,
      },
      {
        id: "6",
        word: "ở phía trên, ở trên",
        wordType: "trạng từ",
        meaning: "Ở một điểm trước đó trong văn bản hoặc tài liệu.",
        examples: ["As mentioned above, we need more time."],
        examplesVi: ["Như đã đề cập ở trên, chúng ta cần thêm thời gian."],
        saved: false,
        popularity: 4,
      },
      {
        id: "7",
        word: "phần trên, nội dung trên",
        wordType: "danh từ",
        meaning: "Cái gì đó được viết hoặc đề cập trước đó trong văn bản.",
        examples: ["The above clearly shows the results."],
        examplesVi: ["Phần trên cho thấy rõ ràng kết quả."],
        saved: false,
        popularity: 3,
      },
      {
        id: "8",
        word: "vượt quá, cao hơn",
        wordType: "giới từ",
        meaning: "Quá tốt hoặc có đạo đức để làm; vượt ra ngoài phạm vi của.",
        examples: ["He thinks he is above such petty behavior."],
        examplesVi: ["Anh ấy nghĩ mình cao hơn những hành vi tầm thường như vậy."],
        saved: false,
        popularity: 2,
      },
    ],
  },
};
