import { HistoryItem, WordDefinition } from "@/types/translation";

export const SAMPLE_HISTORY: HistoryItem[] = [
  { id: "1", word: "performance" },
  { id: "2", word: "suburb" },
  { id: "3", word: "sanity" },
  { id: "4", word: "under the weather" },
  { id: "5", word: "nostalgic" },
];

// Sample word list for suggestions
export const WORD_LIST = [
  "band",
  "bandage",
  "bandaged",
  "bandager",
  "bandagers",
  "bandages",
  "bandaging",
  "banded",
  "banding",
  "bands",
  "bandwidth",
  "book",
  "booking",
  "booklet",
  "bookmark",
  "books",
  "bookshelf",
  "bookstore",
  "performance",
  "perform",
  "performer",
  "performing",
  "suburb",
  "suburban",
  "suburbanite",
  "suburbs",
  "sanity",
  "sane",
  "sanitize",
  "sanitary",
  "nostalgic",
  "nostalgia",
  "hello",
  "help",
  "helpful",
  "helping",
  "helper",
  "world",
  "work",
  "worker",
  "working",
  "workout",
  "workplace",
];

export const SAMPLE_DEFINITIONS: { [key: string]: WordDefinition } = {
  band: {
    word: "band",
    pronunciation: "/bænd/",
    definitions: [
      {
        id: "1",
        word: "ban nhạc",
        wordType: "danh từ",
        meaning: "Nhóm người chơi nhạc cụ và ca hát.",
        examples: ["a rock band", "một ban nhạc rock"],
        examplesVi: [],
        saved: true,
      },
      {
        id: "2",
        word: "dải, vòng, dải",
        wordType: "danh từ",
        meaning: "Một mảnh vải mỏng, phẳng, thun, kim loại hoặc vật liệu khác được quấn quanh vật gì đó.",
        examples: ["a red silk band", "một dải lụa đỏ"],
        examplesVi: [],
        saved: false,
      },
      {
        id: "3",
        word: "nhóm",
        wordType: "danh từ",
        meaning: "Một tập hợp người hoặc đối tượng được phân loại theo một tiêu chí chung.",
        examples: [
          "The former president still has a small band of supporters.",
          "Cựu tổng thống vẫn còn một nhóm nhỏ người ủng hộ.",
        ],
        examplesVi: [],
        saved: false,
      },
      {
        id: "4",
        word: "phạm vi",
        wordType: "danh từ",
        meaning: "Một phạm vi hoặc giới hạn cụ thể (thường dùng trong khoa học hoặc phân loại).",
        examples: [
          "The scheme is devised for young people in the 15-20 age band.",
          "Chương trình này dành cho những người trẻ trong độ tuổi từ 15 đến 20.",
        ],
        examplesVi: [],
        saved: false,
      },
      {
        id: "5",
        word: "gắn vòng",
        wordType: "động từ",
        meaning: "Gắn vòng/đánh dấu bằng vòng/buộc vòng lên vật gì đó, đặc biệt là một con vật.",
        examples: ["We banded the birds.", "Chúng tôi gắn vòng cho những con chim."],
        examplesVi: [],
        saved: false,
      },
    ],
  },
};
